export const USER_LOGGEDIN = "USER_LOGGEDIN";
export const USER_LOGGEDOUT = "USER_LOGGEDOUT";
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const SHEETS_DATA_RECIEVED = "SHEETS_DATA_RECIEVED";
export const ERROR_OCCURED = "ERROR_OCCURED";
export const ERROR_DISMISSED = "ERROR_DISMISSED";
export const ADD_CHART_DATA = "ADD_CHART_DATA";
